### ISSUE TITLE
Not working on IE 11

### ISSUE THREAD

**Issue by rishparekh** [gilf/angular2-indexeddb#40]
Getting following error on ie 11 but same is working on chrome as well as firefox

ERROR Error: Uncaught (in promise): TypeError: Unable to get property 'open' of undefined or null reference
TypeError: Unable to get property 'open' of undefined or null reference
   at Anonymous function (http://localhost:4200/vendor.bundle.js:99486:13)
   at ZoneAwarePromise (http://localhost:4200/polyfills.bundle.js:14503:29)
   at AngularIndexedDB.prototype.createStore (http://localhost:4200/vendor.bundle.js:99484:26)
   at LocalStorageService.prototype.createStores (http://localhost:4200/main.bundle.js:112:9)
   at AppComponent.prototype.ngOnInit (http://localhost:4200/main.bundle.js:7721:9)
   at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:11174:9)
   at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:12596:13)
   at checkAndUpdateNode (http://localhost:4200/vendor.bundle.js:12536:9)
   at prodCheckAndUpdateNode (http://localhost:4200/vendor.bundle.js:13063:5)
   at Anonymous function (Function code:12:5)
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Uncaught (in promise): TypeError: Unable to get property 'open' of undefined or null reference
TypeError: Unable to get property 'open' of undefined or null reference
   at Anonymous function (http://localhost:4200/vendor.bundle.js:99486:13)
   at ZoneAwarePromise (http://localhost:4200/polyfills.bundle.js:14503:29)
   at AngularIndexedDB.prototype.createStore (http://localhost:4200/vendor.bundle.js:99484:26)
   at LocalStorageService.prototype.createStores (http://localhost:4200/main.bundle.js:112:9)
   at AppComponent.prototype.ngOnInit (http://localhost:4200/main.bundle.js:7721:9)
   at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:11174:9)
   at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:12596:13)
   at checkAndUpdateNode (http://localhost:4200/vendor.bundle.js:12536:9)
   at prodCheckAndUpdateNode (http://localhost:4200/vendor.bundle.js:13063:5)
   at Anonymous function (Function code:12:5)",
      message: "Uncaught (in promise): TypeError: Unable to get property 'open' of undefined or null reference
TypeError: Unable to get property 'open' of undefined or null reference
   at Anonymous function (http://localhost:4200/vendor.bundle.js:99486:13)
   at ZoneAwarePromise (http://localhost:4200/polyfills.bundle.js:14503:29)
   at AngularIndexedDB.prototype.createStore (http://localhost:4200/vendor.bundle.js:99484:26)
   at LocalStorageService.prototype.createStores (http://localhost:4200/main.bundle.js:112:9)
   at AppComponent.prototype.ngOnInit (http://localhost:4200/main.bundle.js:7721:9)
   at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:11174:9)
   at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:12596:13)
   at checkAndUpdateNode (http://localhost:4200/vendor.bundle.js:12536:9)
   at prodCheckAndUpdateNode (http://localhost:4200/vendor.bundle.js:13063:5)
   at Anonymous function (Function code:12:5)",
      name: "Error",
      promise: { },
      rejection: { },
      stack: "Error: Uncaught (in promise): TypeError: Unable to get property 'open' of undefined or null reference
TypeError: Unable to get property 'open' of undefined or null reference
   at Anonymous function (http://localhost:4200/vendor.bundle.js:99486:13)
   at ZoneAwarePromise (http://localhost:4200/polyfills.bundle.js:14503:29)
   at AngularIndexedDB.prototype.createStore (http://localhost:4200/vendor.bundle.js:99484:26)
   at LocalStorageService.prototype.createStores (http://localhost:4200/main.bundle.js:112:9)
   at AppComponent.prototype.ngOnInit (http://localhost:4200/main.bundle.js:7721:9)
   at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:11174:9)
   at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:12596:13)
   at checkAndUpdateNode (http://localhost:4200/vendor.bundle.js:12536:9)
   at prodCheckAndUpdateNode (http://localhost:4200/vendor.bundle.js:13063:5)
   at Anonymous function (Function code:12:5)
   at resolvePromise (http://localhost:4200/polyfills.bundle.j",
      Symbol()_m.ysmet5j9mui: undefined,
      Symbol()_n.ysmet5j9mui: undefined,
      Symbol(rxSubscriber)_o.ysmet5j9mui: undefined,
      task: { },
      zone: { }
   }

**Comment by gilf** [comment]
Are you sure you are working on IE11? 
This error indicates that indexedDB isn't available and it is supported since IE10.
Please check your user agent string or your document mode which might be pointing to IE9.

**Comment by rishparekh** [comment]
na. its solved. thanks..
the issue was, i was trying in private mode
